### PR TITLE
Get and preserve refresh token

### LINKED ISSUE #103: Lose auth token after an hour
(FYI this is an upstreaming of https://github.com/rfgamaral/docker-gphotos-uploader/issues/8)

Repro:
1. Download the [latest release](https://github.com/nmrshll/gphotos-uploader-cli/releases) of `gphotos-uploader-cli`.
1. Run `gphotos-uploader-cli init` and change the `config.hjson` with your credentials and e-mail. `SecretsBackendType` can be set to `auto` or `file`; it doesn’t matter.
1. Run `gphotos-uploader-cli` as much as you want in a 10-minute span. Except for prompting for a key for local encryption of the auth token, it works great.
1. Wait an hour.
1. Run `gphotos-uploader-cli`.

What should happen:
It should work. The auth token shouldn’t expire in an hour.

What does happen:
It doesn’t work. It says the token is invalid and kicks you back to the Google auth page. (The auth page immediate re-grants the token, but still.)

### PR DESCRIPTION
**Pull request by pdecat**
Resolves #103 

This depends on https://github.com/nmrshll/oauth2-noserver/pull/5

### CODE REVIEW

**Comment by pacoorozco** [comment]
The problem is that `nmrshll/oauth2-noserver#5` is not being merged. :-(

**Comment by pdecat** [comment]
What about forking that too in https://github.com/gphotosuploader/ ?

**Comment by pacoorozco** [comment]
Hi @pdecat 

It could be an option... the problem is that everytime we do a fork we are accepting to maintain it. This could be more efforts than expected. If the current package is not maintained... can we choose another one? That's why I was suggesting to change the implementation to a better managed package, like `github.com/int128/oauth2cli`.

I don't have an strong opinion... we can transfer the `github.com/nmrshll/oauth2-noserver` package to the org or we can use a new one... **Please feel free to comment your choose.**

**Comment by rfgamaral** [comment]
One question we got ask ourselves is, is @nmrshll going to come back and maintain this project (and it's dependencies) or did he pass the torch to you? If so, I don't see a problem in forking `oauth2-noserver` and maintain that. In fact, maybe we should do that for all repos, even this one? I don't know, just a thought...

However, I don't see a reason why we should not consider `github.com/int128/oauth2cli` as an alternative. Is that a better implementation? Well maintained? More robust an reliable? Does it support headless servers (because that's the main point of `oauth2-noserver`, it's actually in the name)? Does it support the refresh token mechanism automatically (which is the point of this PR)?

If so, maybe we should migrate to that instead :)

**Comment by pacoorozco** [comment]
I don't know if @nmrshll will come back. I asked him to transfer `gphotos-uploader-cli` to this organization, in order to allow us to act faster. 
In open source is common that projects appears and disappears, and the projects that are using the first one as dependencies has to act consequently: forking or changing dependency.
I always try to find well maintained dependencies and to focus my efforts on the things that are not already covered.

**Answering your questions**:
>Is that a better implementation? 

I think so. How the code is implemented is simpler and clearer. It's using more from the go power.

> Well maintained? 

Not sure. It's an implementation maintained by only one guy!. That means that the same could eventually happend.

> More robust an reliable? 

It seems so. More debug messages, better interfaces, less overhead...

> Does it support headless servers (because that's the main point of oauth2-noserver, it's actually in the name)? 

Not sure. I'm not focusing too much in headless support. I know that it's a topic, and I would like to cover it also... but to be honest there are several implementation details that are not currently solved to support headless clients properly. **It's kind of todo item**

> Does it support the refresh token mechanism automatically (which is the point of this PR)?

Yes, in fact... refresh token mechanism is managed by `http.Client` implementation. This package and `oauth2-noserver` also, are only responsible of getting the token from Google Photos.

**Comment by rfgamaral** [comment]
I'd say, use that package. It seems a better solution all-around. If, for some reason, we need to make changes to it and the author is unresponsive, we can always fork it. It's just the nature of open-source.

> Not sure. I'm not focusing too much in headless support. I know that it's a topic, and I would like to cover it also... but to be honest there are several implementation details that are not currently solved to support headless clients properly. It's kind of todo item

Ever since I built my Docker container I had to find workarounds to make the whole thing work headless. It's not 100% automated and I don't think it will ever be given the nature of Google's OAuth for this (I could be wrong). So, as long as future changes still allow me to work around some of those limitations and keep the container working, I'm happy (and so will be my users).

**Comment by pdecat** [comment]
> It could be an option... the problem is that everytime we do a fork we are accepting to maintain it. 

What about doing a _soft fork_, i.e. not changing the package name but using a `replace` in `go.mod`?

```
replace github.com/nmrshll/oauth2-noserver => github.com/gphotosuploader/oauth2-noserver v0.0.0-20190612234004-b0730ae5fd3d
```

If https://github.com/nmrshll/oauth2-noserver/pull/5 eventually gets merged, we can drop the `replace` from `go.mod`.

In the meantime, other alternatives can be evaluated.

**Comment by pacoorozco** [comment]
Hi,

I've finally merged #112, that solves the problem we were discussing.

**Comment by pdecat** [comment]
Hi @pacoorozco,

ok, I'll rebase https://github.com/gphotosuploader/gphotos-uploader-cli/pull/63 and remove it's dependency on nmrshll/oauth2-noserver#5

**Comment by pdecat** [comment]
I believe https://github.com/gphotosuploader/gphotos-uploader-cli/pull/107/commits/d92ec684718b8789be4acb75c22c01960cbe9738 is still necessary to avoid losing the refresh token on token updates.

**Pull request closed without merging**
