### PR TITLE
Add SkipTerminalPrompt setting

### PR DESCRIPTION
**Pull request by danrabinowitz**
**What issue type does this pull request address?** (keep at least one, remove the others)  
/kind feature

**What is this pull request for? Which issues does it resolve?** (use `resolves #<issue_number>` if possible)  
The https://github.com/rfgamaral/docker-gphotos-uploader project applies a patch to make the terminal prompt a noop. This PR is a cleaner solution.

**Does this pull request has user-facing changes?** (e.g. config changes, new/modified commands, new/modified flags)  
Yes. I can add more documentation, but I'm waiting to see if you're interested in this PR first.

**Does this pull request add new dependencies?**  
No

**What else do we need to know?**  
Thanks!

### CODE REVIEW

**Comment by pacoorozco** [comment]
Hi @danrabinowitz 

First of all, thanks a lot for your contribution. I was on vacation and I've started to review the pending PRs.

For this specific one, this change has been requested several times. My concern is that the terminal prompt is a measure to encrypt your credentials in a local store. Otherwise they are kept in plain text, which could imply a security vulnerability for your account access. 

For that reason, I rejected previous requests to change this behaviour. But, I've realised that it could be useful for headless environments. I'm thinking that we can change your approach a bit. 

Instead of using a flag to skip the terminal prompt, we can use a flag (and a environment var) to set the password. With this approach we can ensure that the credentials are encrypted (so we are not opening any security breach) and in headless setup we can use the flag / env var to set the password.

`gphotos-uploader-cli --encrypt-key XYZ` or `GPHOTO_UPLOADER_ENCRYPT_KEY=XYZ gphotos-uploader-cli`

What do you think? Does it makes sense?

**Comment by rfgamaral** [comment]
> in headless setup we can use the flag / env var to set the password.

I just want to add that doing this is pretty much the same as what I'm currently doing, in terms of security that is. I mean, setting and env var for a Docker container (such as the password) will expose that env var's value.

**Comment by pacoorozco** [comment]
Hi @rfgamaral 

I think we have already discussed this in the past. Exposing a flag or environment variable is not the same as keeping credentials in plain text on the disk. 

Environment variables can leak in some circumstances that are less serious than an attacker actually getting interactive shell access to your host (a good article describing some of the possible risks is "[Environment Variables Considered Harmful for Your Secrets](http://movingfast.io/articles/environment-variables-considered-harmful/)" . Also storing secrets in plain text can present risks of an attacker getting access to the unmounted disk, from backups or similar.

As one example, I'm presuming that you backup the config file in some way, so there's a risk of unauthorised access to that backup.

On desktop setups `gphotos-uploader-cli` uses a "secrets management" solution to help manage things like this. But in headless setup all the options needs to use a plain text key.

This idea is not perfect and will not prevent visibility into the “sensitive” variables from prying eyes with access to the host. The variables will still be visible if the container is “inspected” (by running ‘docker inspect’), if the container is attached to and the variables are examined, or if the variables are dumped by logs of the application. It does however prevent the variables from being written in plain text to the disk and only allows the user with the private key to read the configuration.

It's the common way to submit "sensitive" information in all the CI/CD tools (like drone.io, Travis...).

**Comment by rfgamaral** [comment]
> It's the common way to submit "sensitive" information in all the CI/CD tools (like drone.io, Travis...).

Yes, but it's not the same thing. For a CI/CD tool, you set the env variable on your account, on a safe system, it's probably encrypted somehow and then decrypted only when required by the CI/CD tool. If you were to hack the CI/CD system you wouldn't have access to those sensitive env variables.

Let's do an exercise...

Assume you make that change to `gphotos-uploader-cli`, the password is read from an environment variable, for instance `KEYRING_PASSWORD`. Now assume you have a headless server running my Docker container which is using that `gphotos-uploader-cli` and requires the `KEYRING_PASSWORD` environment variable to be set to work.

How and where **exactly** would you configure your container to set the `KEYRING_PASSWORD` environment variable?

**Comment by pacoorozco** [comment]
Unless you were using some secret management tool (like [Docker Secrets](https://docs.docker.com/engine/swarm/secrets/)) you should put it on the script that is launching your Docker. 

As I mentioned before *Environment variables can leak in some circumstances...* (see [above](https://github.com/gphotosuploader/gphotos-uploader-cli/pull/209#issuecomment-668512703)) but it's still more secure than writing credentials directly to a file.

**Comment by rfgamaral** [comment]
> you should put it on the script that is launching your Docker.

> but it's still more secure than writing credentials directly to a file.

Looks the same to me...

> one thing we can use is a big disclaimer when credentials are not encrypted. This would be a way to implement "no encryption". right?

Isn't this PR that already? I mean, if you want to disable encryption you have to explicitly opt-out with the `SkipTerminalPrompt` setting. Just hide it from the default template (so people don't know such option exists) and document the setting with that big disclaimer. Won't that achieve what you want?

**Comment by danrabinowitz** [comment]
I'm just catching up here...

There are different threat models. For some scenarios, such as a local unprivileged user, ENV vars are the less secure option. For some scenarios, such as accidentally backing up files with credentials, files are the less secure option.

I'm not going to debate which is better in the abstract.

I like the idea that @pacoorozco suggested, of having an `--encrypt-key` flag and a `GPHOTO_UPLOADER_ENCRYPT_KEY` env var. That way, an attacker would need both the encryption key (which a local unprivileged user could grab) *and* the file with the encrypted credentials (which could accidentally be backed up). It's somewhat harder for an attacker to obtain both.

**Comment by rfgamaral** [comment]
> I like the idea that @pacoorozco suggested, of having an `--encrypt-key` flag and a `GPHOTO_UPLOADER_ENCRYPT_KEY` env var. That way, an attacker would need both the encryption key (which a local unprivileged user could grab) _and_ the file with the encrypted credentials (which could accidentally be backed up). It's somewhat harder for an attacker to obtain both.

I'm not sure where that idea has been conveyed in this topic. I mean, you're talking about an encryption key **and** a file with encrypted credentials pair; that's the first time I'm hearing about that.

All it was mentioned before was using an environment variable to store a password (instead of using a terminal prompt). And my point is that doing just that or disabling the terminal prompt (like you did in this PR) yields exactly the same thing from a security perspective.

Your idea might be different but I'll refrain from commenting any further until I understand exactly how would that be implemented in a headless environment.

**Comment by danrabinowitz** [comment]
Sorry, I was wrong. I misunderstood how the encryption key was used. Please ignore my earlier comment.

I'm not as familiar with the code as @pacoorozco but I'm fine with an ENV var or a flag.

**Comment by pacoorozco** [comment]
Hi

@danrabinowitz you were right. The requested password by the terminal prompt **is the encription key of a file containing an encrypted version of your credentials** See it [here](https://github.com/gphotosuploader/gphotos-uploader-cli/blob/8a9ac28015976623da7bb7efcba9c9aa7619c411/datastore/tokenstore/repository_keyring.go#L21).

That's why I'm so reluctant to write plain text credentials there.

**Comment by danrabinowitz** [comment]
OK, good. :-)

So what's next @pacoorozco? Are you clear on how to proceed? Is there anything I can do to help?

**Comment by pacoorozco** [comment]
Hi! This has been implemented in a different PR #236 . You can find the documentation [here](https://github.com/gphotosuploader/gphotos-uploader-cli/blob/master/.docs/configuration.md#environment-variables)

**Pull request closed without merging**
